### ISSUE TITLE
Feature Request: API for FAE 2.0

### ISSUE THREAD

**Issue by khays9** [opena11y/fae#28]
It would be helpful to have an API for FAE 2.0 so that an instance of FAE could be set up in a development environment and fully streamlined into continuous integration testing. The ability to allow the test environment to execute one or more FAE rules and act based on the result is needed for this type of integration.

**Comment by jongund** [comment]
I you looking for more of a:
1. browser/DOM inspector plug-in (similar to aXe extension for Chrome) that will run against the current DOM?
2. Analyze a URL using FAE 2,0 and return results as a JSON or other object
3. or something else entirely?

**Comment by khays9** [comment]
Jon,

They’re not completely sure yet what they want to do yet.  There is talk of running using Selenium, which would simply need analyze the current DOM and return a JSON object to parse, I think. This is developing a bit slowly, so I’ll get back to you once I hear more.

The important part is the need to run or own instance and have parsable data for the testing scripts.

Thanks,
Keith
--
Keith Hays
Senior Information Design Specialist — Accessibility
Technology Services, University of Illinois at Urbana-Champaign
DCL RM1441   4-8519
