### ISSUE TITLE
Add an API for integration and/or unit testing

### ISSUE THREAD

**Issue by kensgists** [opena11y/fae#29]
Tenon and aXe both have APIs that allow a developer, using Jasmine with Selenium, etc., to either pass a url or rendered document source/source fragment and have the frameworks return responses as JSON objects. 

FAE's robust ruleset and openness could lead to strong adoption if there were an API.

**Comment by brandonneil** [comment]
This would be a great addition. We would like to kick off an accessibility check when we do a deployment into one of our hosting environments as part of our development workflow. It would then be great to return the results of the check via an api endpoint.

**Comment by brandonneil** [comment]
Related #28
