### ISSUE TITLE
Empty results for evaluation

### ISSUE THREAD

**Issue by jongund** [opena11y/fae#31]
Illinois School for the  Visually Impaired evaluation does not seem to find any content for the website and reports all rules as not applicable.

http://isvi.net/ 

Maybe a timing issue due to a toolbar for customizing the rendering of content

**Comment by mike-scott-illinois-gov** [comment]
Deeper pages don't have the "ATBar" toolbar that is on the home page (http://isvi.net/index.html), but still seem to have the all-rules-not-applicable problem. Use http://isvi.net/Staff.html as an example. FAE should find several links with no text content
