### ISSUE TITLE
Apache Config

### ISSUE THREAD

**Issue by timthedevguy** [opena11y/fae#43]
Upon attempting to use sample config it would keep failing on this line:

WSGIScriptAlias [absolute path]/fae2/fae2/wsgi.py

After some research I believe it's supposed to look like this:

WSGIScriptAlias / [absolute path]/fae2/fae2/wsgi.py

Disclaimer: I come from an Apache2/Symfony/PHP, Windows IIS/C# background, this is my first adventure in to Python/Django..so please excuse me if I make a mistake.

**Comment by LauraOU** [comment]
Also, the "sample apache file" seems to have one too many /fae/ subdirectories:
  Alias /static /var/www/fae2/fae2/fae2/fae2/static/
