### ISSUE TITLE
Missing /static/admin/ folders

### ISSUE THREAD

**Issue by timthedevguy** [opena11y/fae#45]
Repository is missing the /static/admin/css, /static/admin/fonts and /static/admin/img folders

**Comment by jongund** [comment]
You need to run collectstatic to create a “run” time collection of all the CSS files.

https://docs.djangoproject.com/en/1.10/ref/contrib/staticfiles/


Jon

**Comment by binarygod** [comment]
Thank you! As a side question, I have recently install FAE on Ubuntu 16 to play with, would you like step by step instructions on this procedure put in your Wiki?
