### ISSUE TITLE
When specified path is two levels, FAE only evaluates top page

### ISSUE THREAD

**Issue by LauraOH** [opena11y/fae#51]
When specifying a path that is two levels, FAE only evaluates the initial page. For example,

http://www.illinois.edu/1st/2nd/

Requiring the path /1st/2nd/, FAE will only evaluate the page at /1st/2nd/.

Looking in the logs from my install, when trying to evaluate pages linked off that initial page, it looks like FAE is appending the required path twice on subpage; i.e. in the included page

http://www.illinois.edu/1st/2nd/linkedpage.htm

It tries to evaluate
http://www.illinois.edu/1st/2nd/1st/2nd/linkedpage.htm
and fails with a 404.

**Comment by jongund** [comment]
Can you send me the information in each form field and options you used?
