### ISSUE TITLE
Role="none presentation"

### ISSUE THREAD

**Issue by LauraOH** [opena11y/fae#52]
FYI, W3C validator warns that "role=none" is not yet accepted by all browsers and recommends "role='none presentation'." FAE flags having these two roles as a violation. 

Page with three examples to test https://codepen.io/LauraFO/full/qYEVWQ/

**Comment by jongund** [comment]
Thank you for reporting this issue, and I will look at getting the bug fixed.
From a functional point over view role "presentation" alone will be supported for a long time.
