### ISSUE TITLE
Unable to login to FAE site - Tried new account and existing.

### ISSUE THREAD

**Issue by AmandaPixo** [opena11y/fae#53]
Steps to reproduce:

1. Navigate to https://fae.disability.illinois.edu/registration/login/
2. Attempt to login using credentials - Fails
3. Tried resetting credentials, this failed to same error
4. Tried creating another login, i.e. Registered again with different email, it failed. 
![screen shot 2018-05-04 at 2 37 37 pm](https://user-images.githubusercontent.com/38990900/39649268-db44e304-4faa-11e8-9318-78ca5f1bd0e5.png)

**Comment by adaminfinitum** [comment]
I was able to register and create a new account in August of 2019, may not be a current problem.
