### ISSUE TITLE
Error: Could not find or load main class org.fae.util.FaeUtil

### ISSUE THREAD

**Issue by gemgin** [opena11y/fae#60]
./run -c test.properties
Error: Could not find or load main class org.fae.util.FaeUtil

**Comment by gemgin** [comment]
[{"status": "C", "slug": "16ef33fb4a093973", "title": "711", "url": "http://www.rrbay.com/wza/", "report_page_url": "", "page_count": 0, "depth": 2, "id": "r15", "report_url": "/summary/16ef33fb4a093973/rc/", "ruleset": "HTML5 and ARIA Techniques", "date": "2019-12-10T22:37:48.836-06:00", "ruleset_url": "/rulesets/ruleset/ARIA_STRICT/", "archive": false}, {"status": "C", "slug": "16ef33675a313e18", "title": "722", "url": "http://www.rrbay.com/wza/", "report_page_url": "", "page_count": 0, "depth": 2, "id": "r14", "report_url": "/summary/16ef33675a313e18/rc/", "ruleset": "HTML4 Legacy Techniques", "date": "2019-12-10T22:27:42.886-06:00", "ruleset_url": "/rulesets/ruleset/ARIA_TRANS/", "archive": false}, {"status": "C", "slug": "16ef32c475bf6f66", "title": "744", "url": "http://www.rrbay.com/wza/", "report_page_url": "", "page_count": 0, "depth": 2, "id": "r13", "report_url": "/summary/16ef32c475bf6f66/rc/", "ruleset": "HTML5 and ARIA Techniques", "date": "2019-12-10T22:16:35.679-06:00", "ruleset_url": "/rulesets/ruleset/ARIA_STRICT/", "archive": false}, {"status": "C", "slug": "16ef31758e585e72", "title": "955", "url": "http://www.rrbay.com/wza/", "report_page_url": "", "page_count": 0, "depth": 2, "id": "r12", "report_url": "/summary/16ef31758e585e72/rc/", "ruleset": "HTML5 and ARIA Techniques", "date": "2019-12-10T21:53:43.913-06:00", "ruleset_url": "/rulesets/ruleset/ARIA_STRICT/", "archive": false}, {"status": "C", "slug": "16ef30c094003269", "title": "966", "url": "http://www.rrbay.com/wza/", "report_page_url": "", "page_count": 0, "depth": 2, "id": "r11", "report_url": "/summary/16ef30c094003269/rc/", "ruleset": "HTML5 and ARIA Techniques", "date": "2019-12-10T21:41:22.627-06:00", "ruleset_url": "/rulesets/ruleset/ARIA_STRICT/", "archive": false}, {"status": "C", "slug": "16ef2f260dfb994e", "title": "977", "url": "http://www.rrbay.com/wza/", "report_page_url": "", "page_count": 0, "depth": 2, "id": "r10", "report_url": "/summary/16ef2f260dfb994e/rc/", "ruleset": "HTML5 and ARIA Techniques", "date": "2019-12-10T21:13:21.122-06:00", "ruleset_url": "/rulesets/ruleset/ARIA_STRICT/", "archive": false}, {"status": "C", "slug": "16ef2f1431d56b42", "title": "988", "url": "http://www.rrbay.com/wza/", "report_page_url": "", "page_count": 0, "depth": 2, "id": "r9", "report_url": "/summary/16ef2f1431d56b42/rc/", "ruleset": "HTML5 and ARIA Techniques", "date": "2019-12-10T21:12:07.969-06:00", "ruleset_url": "/rulesets/ruleset/ARIA_STRICT/", "archive": false}, {"status": "D", "slug": "16ef2ec71854c5ac", "title": "1231sdfsdf", "url": "http://www.rrbay.com/wza/", "report_page_url": "", "page_count": 0, "depth": 2, "id": "r8", "report_url": "/summary/16ef2ec71854c5ac/rc/", "ruleset": "HTML5 and ARIA Techniques", "date": "2019-12-10T21:06:52.168-06:00", "ruleset_url": "/rulesets/ruleset/ARIA_STRICT/", "archive": false}, {"status": "D", "slug": "16ef2e7b88801c77", "title": "wza", "url": "http://www.rrbay.com/wza/", "report_page_url": "", "page_count": 0, "depth": 2, "id": "r7", "report_url": "/summary/16ef2e7b88801c77/rc/", "ruleset": "HTML5 and ARIA Techniques", "date": "2019-12-10T21:01:42.668-06:00", "ruleset_url": "/rulesets/ruleset/ARIA_STRICT/", "archive": false}, {"status": "D", "slug": "16ef2e6000033cad", "title": "sdf213213", "url": "http://www.rrbay.com/wza/", "report_page_url": "", "page_count": 0, "depth": 2, "id": "r6", "report_url": "/summary/16ef2e6000033cad/rc/", "ruleset": "HTML5 and ARIA Techniques", "date": "2019-12-10T20:59:49.892-06:00", "ruleset_url": "/rulesets/ruleset/ARIA_STRICT/", "archive": false}, {"status": "D", "slug": "16ef2e417af3e08a", "title": "123213", "url": "http://www.rrbay.com/", "report_page_url": "", "page_count": 0, "depth": 2, "id": "r5", "report_url": "/summary/16ef2e417af3e08a/rc/", "ruleset": "HTML5 and ARIA Techniques", "date": "2019-12-10T20:57:44.882-06:00", "ruleset_url": "/rulesets/ruleset/ARIA_STRICT/", "archive": false}, {"status": "D", "slug": "16ef2e299599d3a4", "title": "2323", "url": "http://www.rrbay.com/", "report_page_url": "", "page_count": 0, "depth": 2, "id": "r4", "report_url": "/summary/16ef2e299599d3a4/rc/", "ruleset": "HTML5 and ARIA Techniques", "date": "2019-12-10T20:56:07.004-06:00", "ruleset_url": "/rulesets/ruleset/ARIA_STRICT/", "archive": false}, {"status": "D", "slug": "16ef2dda47ef59ba", "title": "xxx", "url": "http://www.qqqao.com", "report_page_url": "", "page_count": 0, "depth": 2, "id": "r3", "report_url": "/summary/16ef2dda47ef59ba/rc/", "ruleset": "HTML5 and ARIA Techniques", "date": "2019-12-10T20:50:42.178-06:00", "ruleset_url": "/rulesets/ruleset/ARIA_STRICT/", "archive": false}, {"status": "D", "slug": "16ef2dc1d343ccd4", "title": "\u592a\u9633\u6e7e\u79d1\u6280", "url": "http://www.rrbay.com/", "report_page_url": "", "page_count": 0, "depth": 2, "id": "r2", "report_url": "/summary/16ef2dc1d343ccd4/rc/", "ruleset": "HTML5 and ARIA Techniques", "date": "2019-12-10T20:49:02.006-06:00", "ruleset_url": "/rulesets/ruleset/ARIA_STRICT/", "archive": false}, {"status": "D", "slug": "16ef2d3451d6ce25", "title": "\u592a\u9633\u6e7e\u79d1\u6280", "url": "http://www.rrbay.com/", "report_page_url": "", "page_count": 0, "depth": 3, "id": "r1", "report_url": "/summary/16ef2d3451d6ce25/rc/", "ruleset": "HTML5 and ARIA Techniques", "date": "2019-12-10T20:39:22.400-06:00", "ruleset_url": "/rulesets/ruleset/ARIA_STRICT/", "archive": false}]

**Comment by jongund** [comment]
What does your class path look like?

**Comment by gemgin** [comment]
how to set class path?

fae-util path is :
/var/www/fae2/fae2/fae2/fae-util

**Comment by gemgin** [comment]
env|grep FAE_HOME
FAE_HOME=/var/www/fae2/fae2/fae2/fae-util

**Comment by jongund** [comment]
Did you use the build script to make the class files?

**Comment by gemgin** [comment]
thanks
