### ISSUE TITLE
AUTHENTICATION_BACKENDS question

### ISSUE THREAD

**Issue by adaminfinitum** [opena11y/fae#67]
**Introduction:**
I am working on my own [fork of FAE](https://github.com/ADA-First/fae2), customizing it to my needs, but the majority of my experiences with Django are with this app and so it's difficult for me to evaluate the "correctness" of settings as I just assume the code here is valid...because the application works, or at least it did in December 2019, when I had a developer set it up for me on Google Kubernetes Engine.

This will be the first of at least a few questions, but I will try to limit each question to a single topic to make it more manageable and useful to others; I'll skip the introduction in future questions.

**Question:**
I was hoping to implement a security-related app, `django-axes`, it's kinda like **Fail2Ban** for Django. It [tracks login attempts and then blocks users](https://django-axes.readthedocs.io/en/latest/2_installation.html) that have repeated, unsuccessful login attempts.

The setup seemed simple and there were no obvious conflicts.

But step 2 on the page linked above says:

> **Add axes.backends.AxesBackend to the top of AUTHENTICATION_BACKENDS:**
> ```
> AUTHENTICATION_BACKENDS = [
>     # AxesBackend should be the first backend in the AUTHENTICATION_BACKENDS list.
>     'axes.backends.AxesBackend',
> 
>     # Django ModelBackend is the default authentication backend.
>     'django.contrib.auth.backends.ModelBackend',
> ]
> ```

When I looked through `base.py` to find the settings for `AUTHENTICATION_BACKENDS` that I needed to prepend the relevant code to, I couldn't find it.

The only reference to `AUTHENTICATION_BACKENDS` that I could see appears to be in the Shibboleth settings and because I'm not affiliated with an academic institution, I'm not--and can't imagine I ever will be--using Shibboleth.

I searched the entire project for `auth` and found other references to it, and I know from using it that there is authentication in use but I can't figure out what the "default" settings would be or how I would add the code needed for the `django-axes` app...can you help me figure out how to set this up?

**Comment by jongund** [comment]
@adaminfinitum 

We are using [django-registration 3.0](https://django-registration.readthedocs.io/en/3.1/) so I am thinking that app is adding the backend.  So you could look at that code to see how it is adding it and maybe create a patch to add the reference.

**Comment by adaminfinitum** [comment]
That's right...it hadn't even occurred to me but I am aware of that app being used...I first started working on FAE2.0 and I think you introduced django-registration in 2.1.

Thanks.
