### ISSUE TITLE
django-timezone-field question

### ISSUE THREAD

**Issue by adaminfinitum** [opena11y/fae#68]
In `requirements.txt` one of the apps that is installed/required is `django-timezone-field` and in my fork of **FAE 2.1**, I am updating the apps included to the latest stable versions which are said to be compatible with Django 2.2.12.

As such, I am looking over the documentation in detail.

In the [docs for `django-timezone-field`](https://pypi.org/project/django-timezone-field/) it says that after installation, it needs to be included in `INSTALLED_APPS` yet there is no reference to it in the current code base.

In my reading about Django I have seen a couple vague references to things that make me think it might be possible for apps that are installed to work without being listed in installed apps but when I am uncertain--like now--I usually just follow the documentation precisely.

Is the code they recommend (shown below) required for it to work? If it is, I assume I should add it to `base.py`?
```
INSTALLED_APPS = (
    ...
    'timezone_field',
    ...
)
```
Or is it just a relic from a previous version that can be removed from `requirements.txt` file?

Thanks for your help.

**Comment by jongund** [comment]
@adaminfinitum 

Thank you for your interest in FAE and reviewing the code for issues like tis.
I think this is a bug, do you have time to do some testing and then do a pull request?

Also are the modifications to FAE something that might be of more general interest to me or the accessibility community?

**Comment by adaminfinitum** [comment]
I think the modifications might be of interest to you or others.

For instance, I made a branch that removes the hardcoded Google Analytics snippet (anyone that sets up an instance of FAE that doesn't edit or remove that snippet will push data to your Google Analytics property and that will make the data unreliable) and replaces it with a Google Tag Manager app (and the account ID is only listed in `secrets.json` which is excluded from version control).

Another branch loads the HTML5 Shim from a CDN because the link currently in use in the project isn't served with Gzip.

I tried to keep the scope of each branch limited to a single "feature" and named in an obvious way so they are easy to merge.

I'm in the process of setting up a localhost virtual machine that matches my production environment (using Vagrant) and hope to be debugging and testing the updates I have made this week...so I'm almost certain to have more questions, issues and updates--but as of now, the updates/changes are still untested.

I'll update these threads as I know more.

**Comment by adaminfinitum** [comment]
I [created a branch](https://github.com/ADA-First/fae2/tree/add-timezone-to-installed-apps) in which I added the `timezone_field` to the `INSTALLED_APPS` in `base.py`.

However, you'd want to ignore updates in any other files in that branch (I rolled back `base.py` in that branch to be totally compatible with the original, but I didn't roll back changes I had made in other files--I'm still mastering branching and merging in git).
